### ISSUE TITLE
Need Reset Board Button on Emulator

### ISSUE THREAD

**Issue by rbaker26** [rbaker26/SAP1EMU#109]
**Description:**
The Emulator Page will be zero-ed out when the user resubmits code to the API

**Comment by BryceCallender** [comment]
Currently was working on this. I currently have it reset the whole board when they submit a new code to the backend.

**Comment by rbaker26** [comment]
> Currently was working on this. I currently have it reset the whole board when they submit a new code to the backend.

sounds good
