### ISSUE TITLE
Investigate Engine Slowdown

### ISSUE THREAD

**Issue by rbaker26** [rbaker26/SAP1EMU#124]
## Where was the bug located
 - [ ] Assembler CLI
 - [ ] Emulator CLI
 - [ ] Emulator / Assembler GUI
 - [x] API  / Library

## Bug Description 

Execution of Benchmark EngineRun_FIB5 has nearly doubled in time. 
Why did this happen.
Check PRs to see when this first happened and see if we can correct the issue.

## Screenshots (If applicable)

![image](https://user-images.githubusercontent.com/31376573/95952223-8f9e8a00-0dac-11eb-872f-c33814de550e.png)

**Comment by BryceCallender** [comment]
I noticed that change with my pull request in #112 . Currently trying to investigate if it was indeed my ALU and IR changes.

**Comment by rbaker26** [comment]
it also *could* be GitHub kicking us down a compute tier, but that seams less likely 
if it is the code, it has to be some iterative or recursive change to blowup the benchmark like that

**Comment by BryceCallender** [comment]
Ya I'm not sure if its my code. IR, only on active low, will do a substring command and the ALU is doing a check whether or not it can set a flag based on that condition and a result. The Instance().function shouldn't be taking up much time either. I might be missing something but my computer gets around this time with some super small optimizations to my ALU calculations.

![image](https://user-images.githubusercontent.com/25470163/96524107-31e6c380-122c-11eb-8995-1f4553745508.png)

**Comment by rbaker26** [comment]
this doesn't seam to be an issue on our side
we can revisit this if necessary
