### ISSUE TITLE
Emulator Hangs - No Error Message

### ISSUE THREAD

**Issue by rbaker26** [rbaker26/SAP1EMU#139]
## Where was the bug located
 - [ ] Assembler CLI
 - [ ] Emulator CLI
 - [x] Emulator / Assembler GUI
 - [ ] API  / Library

## Bug Description 

The following code does not produce an error nor does it run.
![image](https://user-images.githubusercontent.com/31376573/96900446-f4aa4d80-1446-11eb-8212-1703ba735c34.png)

## Steps to Reproduce (for bugs)

1. Type the following code into the Emulator
3. Set Set to BenEaster
3. Click Run
4. Notice RAM doesnt update 
5. Notice No Error is producted

## Expected Behavior

This should generate the "needs 16 lines of code error 

## Screenshots
DB Tables
![image](https://user-images.githubusercontent.com/31376573/96901072-a77aab80-1447-11eb-92a3-1a384ee1c6f6.png)

## Context

I found this code in the DB, so a user submitted this code and nothing happened for them.
This is a bad user experience.

**Comment by rbaker26** [comment]
@BryceCallender 
If you have time, can you also add a short integration test to cover this case?
It's nice to have coverage of issues once we fix them.

**Comment by BryceCallender** [comment]
Yup I was planning on doing that!
